// data.js
// The real watch order: every mainline Marvel Cinematic Universe movie and
// series, the Disney+ "side story" shows, the pre-Disney+ "Netflix corner"
// (Daredevil, Jessica Jones, The Punisher) that Daredevil: Born Again
// directly continues, and Fox's X-Men series — folded in as its own block
// ahead of Deadpool & Wolverine, which pulls it into the main multiverse.
// Covers everything from Iron Man (2008) through Avengers: Doomsday
// (Dec 18, 2026).
//
// This is an independent, fan-made list — not an official Marvel Studios,
// Disney, Netflix, Fox, or Sony publication. Release dates and runtimes are
// drawn from public sources; timelineOrder reflects the commonly cited
// fan-consensus in-universe chronology (not an official numbered canon —
// Marvel has never published one).
//
// releaseOrder is a curated recommended-watch order, not strictly real-world
// release date — e.g. Black Widow (2021) sits right after Civil War (2016)
// because that's when its story happens, and the Street-Level Track
// (Daredevil/Jessica Jones/Punisher, 2015-2019) sits right before Daredevil:
// Born Again rather than off in its own appended block. Every such exception
// is called out in that item's own notes. The X-Men Homework Pack and the
// optional side quests are still their own contiguous blocks rather than
// interleaved by date, since they're genuinely separate content, not part
// of the main recommended sequence. timelineOrder is the separate
// in-universe chronological view: the X-Men Homework Pack sits at the point
// it's pulled into the main story via a multiverse crossover (not a literal
// claim it shares Earth-616's timeline), and the Street-Level Track plus the
// optional side quests sit as contiguous blocks right before Daredevil:
// Born Again — the point they're actually relevant to watch — rather than
// scattered across their real-world airdates.
//
// Shape of each item:
//   id             - unique string, used as the localStorage key (for movies)
//   title          - display name
//   type           - "movie" | "show"
//   releaseOrder   - integer, position in the curated recommended watch order
//   timelineOrder  - integer, position in in-universe chronological order
//   section        - id of the section (see `sections` below) this item's
//                    releaseOrder position falls under. Section grouping
//                    (headers, per-section progress, "mark all watched") is
//                    a release-order-only concept — timelineOrder view
//                    renders as a flat list, since sections describe "the
//                    recommended path," not chronology.
//   core           - true for the subset flagged as essential, must-not-skip
//                    viewing, shown with a CORE badge. Everything else in a
//                    required section is still required — core just marks
//                    the highlights within it.
//   runtimeMinutes - movies only; total watch time in minutes
//   spoiler        - movies only; a short note on how this movie's ending
//                    or post-credits scene connects to the wider story —
//                    hidden behind a tap-to-reveal warning, same as the
//                    per-episode one below. Only movies with a genuine
//                    forward-connecting reveal carry one.
//   episodes       - shows only; array of { id, title, runtimeMinutes, spoiler? } —
//                    each episode id is its own localStorage key, so
//                    progress is tracked per episode, not per show.
//                    spoiler, where present, is a short note on how that
//                    episode connects to the wider story — hidden behind
//                    a tap-to-reveal warning in the UI, never shown by
//                    default. Most episodes have none; only the ones with
//                    a genuine connection (a reveal, a setup for another
//                    title) carry one — this isn't a full recap.
//   notes          - optional short blurb shown under the title
//   stopPoint      - optional string shown as a prominent warning callout,
//                    e.g. "Stop before the post-credits scene — it's a
//                    flash-forward that only makes sense once you reach
//                    Hawkeye."
//   optional       - true for "side quest" content (the Raimi/Garfield-era
//                    Spider-Man films, the First Class-era X-Men films,
//                    Agents of S.H.I.E.L.D., Luke Cage, Iron Fist, The
//                    Defenders, Jessica Jones Seasons 2-3, and What If...?
//                    Seasons 2-3) that doesn't feed into Doomsday directly.
//                    Hidden from the list and excluded from the stats bar
//                    unless the "Include optional side quests" switch is on.

// Sections group consecutive releaseOrder positions into the named "parts"
// of the recommended watch order (Release order view only — see above).
// `range` is [firstReleaseOrder, lastReleaseOrder], inclusive.
export const sections = [
  { id: "infinity-saga", title: "The Infinity Saga", description: "Movies only — the entire Infinity Saga arc, start to finish.", range: [1, 24] },
  { id: "street-level", title: "The Street-Level Track", description: "The pre-Disney+ Netflix corner — required here because Daredevil: Born Again picks up directly from it.", range: [25, 30] },
  { id: "multiverse-saga", title: "The Multiverse Saga: Phases 4-5", description: "The Disney+ era begins — the multiverse rules set up here carry all the way through to Doomsday.", range: [31, 50] },
  { id: "x-men-pack", title: "The X-Men Homework Pack", description: "Fox's mutant timeline, watched as its own block before it collides with the main story.", range: [51, 58] },
  { id: "final-run", title: "The Final Run", description: "Everything still airing or about to, right up to Avengers: Doomsday itself.", range: [59, 70] },
  { id: "side-quests", title: "Optional Side Quests", description: "Side content that doesn't feed into Doomsday directly — switch on to include.", range: [71, 96] },
];

export const items = [
  { id: "iron-man", title: "Iron Man", type: "movie", releaseOrder: 1, timelineOrder: 3, section: "infinity-saga", runtimeMinutes: 126, spoiler: "The post-credits scene is the birth of the MCU: Nick Fury reveals S.H.I.E.L.D. and the first mention of the Avenger Initiative." },
  { id: "incredible-hulk", title: "The Incredible Hulk", type: "movie", releaseOrder: 2, timelineOrder: 5, section: "infinity-saga", runtimeMinutes: 112, notes: "Often skipped today — Mark Ruffalo replaces Edward Norton as Banner from here on." },
  { id: "iron-man-2", title: "Iron Man 2", type: "movie", releaseOrder: 3, timelineOrder: 4, section: "infinity-saga", runtimeMinutes: 124 },
  { id: "thor", title: "Thor", type: "movie", releaseOrder: 4, timelineOrder: 6, section: "infinity-saga", runtimeMinutes: 115 },
  { id: "captain-america-first-avenger", title: "Captain America: The First Avenger", type: "movie", releaseOrder: 5, timelineOrder: 1, section: "infinity-saga", runtimeMinutes: 124 },
  { id: "the-avengers", title: "The Avengers", type: "movie", releaseOrder: 6, timelineOrder: 7, section: "infinity-saga", runtimeMinutes: 143, spoiler: "The post-credits scene reveals Thanos smiling at the thought of claiming the Infinity Stones himself — the whole Infinity Saga's endgame, foreshadowed here first." },
  { id: "iron-man-3", title: "Iron Man 3", type: "movie", releaseOrder: 7, timelineOrder: 8, section: "infinity-saga", runtimeMinutes: 130 },
  { id: "thor-dark-world", title: "Thor: The Dark World", type: "movie", releaseOrder: 8, timelineOrder: 9, section: "infinity-saga", runtimeMinutes: 112 },
  { id: "captain-america-winter-soldier", title: "Captain America: The Winter Soldier", type: "movie", releaseOrder: 9, timelineOrder: 10, section: "infinity-saga", runtimeMinutes: 136, spoiler: "S.H.I.E.L.D. is revealed to have been infiltrated by Hydra from the start and collapses entirely — and Bucky Barnes, Steve's best friend, is the brainwashed assassin the Winter Soldier." },
  { id: "guardians-of-the-galaxy", title: "Guardians of the Galaxy", type: "movie", releaseOrder: 10, timelineOrder: 11, section: "infinity-saga", runtimeMinutes: 121 },
  { id: "guardians-of-the-galaxy-vol-2", title: "Guardians of the Galaxy Vol. 2", type: "movie", releaseOrder: 11, timelineOrder: 12, section: "infinity-saga", runtimeMinutes: 136 },
  { id: "avengers-age-of-ultron", title: "Avengers: Age of Ultron", type: "movie", releaseOrder: 12, timelineOrder: 15, section: "infinity-saga", core: true, runtimeMinutes: 141, spoiler: "Ultron is destroyed, a new Avengers roster forms around Cap and War Machine, and Thanos finally moves to collect the Infinity Stones himself." },
  { id: "ant-man", title: "Ant-Man", type: "movie", releaseOrder: 13, timelineOrder: 16, section: "infinity-saga", runtimeMinutes: 117 },
  { id: "captain-america-civil-war", title: "Captain America: Civil War", type: "movie", releaseOrder: 14, timelineOrder: 18, section: "infinity-saga", runtimeMinutes: 147, spoiler: "The Avengers fracture into two camps over accountability and Bucky's innocence — Cap and Tony's friendship breaks, and the team stays split all the way to Infinity War." },
  { id: "black-widow", title: "Black Widow", type: "movie", releaseOrder: 15, timelineOrder: 19, section: "infinity-saga", core: true, runtimeMinutes: 134, notes: "Moved here in release order even though it came out in 2021 — the story happens right after Civil War, and that's where it lands best.", spoiler: "A post-credits scene has Valentina de Fontaine approach Yelena Belova at Natasha's grave and give her a new target — the setup that eventually leads into Thunderbolts*." },
  { id: "doctor-strange", title: "Doctor Strange", type: "movie", releaseOrder: 16, timelineOrder: 22, section: "infinity-saga", runtimeMinutes: 115 },
  { id: "spider-man-homecoming", title: "Spider-Man: Homecoming", type: "movie", releaseOrder: 17, timelineOrder: 21, section: "infinity-saga", runtimeMinutes: 133 },
  { id: "thor-ragnarok", title: "Thor: Ragnarok", type: "movie", releaseOrder: 18, timelineOrder: 23, section: "infinity-saga", runtimeMinutes: 130 },
  { id: "black-panther", title: "Black Panther", type: "movie", releaseOrder: 19, timelineOrder: 20, section: "infinity-saga", core: true, runtimeMinutes: 134 },
  { id: "avengers-infinity-war", title: "Avengers: Infinity War", type: "movie", releaseOrder: 20, timelineOrder: 28, section: "infinity-saga", runtimeMinutes: 149, spoiler: "Thanos collects all six Infinity Stones and snaps away half of all life in the universe, including most of the Avengers themselves." },
  { id: "ant-man-and-the-wasp", title: "Ant-Man and the Wasp", type: "movie", releaseOrder: 21, timelineOrder: 27, section: "infinity-saga", runtimeMinutes: 118 },
  { id: "captain-marvel", title: "Captain Marvel", type: "movie", releaseOrder: 22, timelineOrder: 2, section: "infinity-saga", runtimeMinutes: 123, notes: "Set in 1995 — chronologically early despite its release date." },
  { id: "avengers-endgame", title: "Avengers: Endgame", type: "movie", releaseOrder: 23, timelineOrder: 29, section: "infinity-saga", runtimeMinutes: 181, notes: "The Infinity Saga payoff. Essential.", spoiler: "Time travel undoes the Snap, Tony Stark sacrifices himself to defeat Thanos for good, and Steve Rogers hands the shield to Sam Wilson — setting up The Falcon and the Winter Soldier." },
  { id: "spider-man-far-from-home", title: "Spider-Man: Far From Home", type: "movie", releaseOrder: 24, timelineOrder: 44, section: "infinity-saga", runtimeMinutes: 129 },
  {
    id: "daredevil-season-1", title: "Daredevil (Season 1)", type: "show", releaseOrder: 25, timelineOrder: 13, section: "street-level",
    notes: "The Netflix corner: Matt Murdock's origin as Daredevil, and Wilson Fisk's rise as Kingpin. Placed here as backstory for Daredevil: Born Again, though it originally aired in 2015.",
    episodes: [
      { id: "daredevil-season-1-e1", title: "Into the Ring", runtimeMinutes: 54 },
      { id: "daredevil-season-1-e2", title: "Cut Man", runtimeMinutes: 54 },
      { id: "daredevil-season-1-e3", title: "Rabbit in a Snowstorm", runtimeMinutes: 53 },
      { id: "daredevil-season-1-e4", title: "In the Blood", runtimeMinutes: 49 },
      { id: "daredevil-season-1-e5", title: "World on Fire", runtimeMinutes: 47 },
      { id: "daredevil-season-1-e6", title: "Condemned", runtimeMinutes: 50 },
      { id: "daredevil-season-1-e7", title: "Stick", runtimeMinutes: 50 },
      { id: "daredevil-season-1-e8", title: "Shadows in the Glass", runtimeMinutes: 50 },
      { id: "daredevil-season-1-e9", title: "Speak of the Devil", runtimeMinutes: 49 },
      { id: "daredevil-season-1-e10", title: "Nelson v. Murdock", runtimeMinutes: 50 },
      { id: "daredevil-season-1-e11", title: "The Path of the Righteous", runtimeMinutes: 49 },
      { id: "daredevil-season-1-e12", title: "The Ones We Leave Behind", runtimeMinutes: 49 },
      { id: "daredevil-season-1-e13", title: "Daredevil", runtimeMinutes: 61, spoiler: "Matt Murdock puts on the horned Daredevil suit for the first time and puts Wilson Fisk behind bars — the status quo Daredevil: Born Again opens by upending." },
    ],
  },
  {
    id: "jessica-jones-season-1", title: "Jessica Jones (Season 1)", type: "show", releaseOrder: 26, timelineOrder: 14, section: "street-level",
    notes: "Netflix corner. Jessica Jones' origin and her fight against Kilgrave — set in the same Hell's Kitchen as Daredevil.",
    episodes: [
      { id: "jessica-jones-season-1-e1", title: "AKA Ladies Night", runtimeMinutes: 48 },
      { id: "jessica-jones-season-1-e2", title: "AKA Crush Syndrome", runtimeMinutes: 48 },
      { id: "jessica-jones-season-1-e3", title: "AKA It's Called Whiskey", runtimeMinutes: 48 },
      { id: "jessica-jones-season-1-e4", title: "AKA 99 Friends", runtimeMinutes: 48 },
      { id: "jessica-jones-season-1-e5", title: "AKA The Sandwich Saved Me", runtimeMinutes: 48 },
      { id: "jessica-jones-season-1-e6", title: "AKA You're a Winner!", runtimeMinutes: 48 },
      { id: "jessica-jones-season-1-e7", title: "AKA Top Shelf Perverts", runtimeMinutes: 48 },
      { id: "jessica-jones-season-1-e8", title: "AKA WWJD?", runtimeMinutes: 48 },
      { id: "jessica-jones-season-1-e9", title: "AKA Sin Bin", runtimeMinutes: 48 },
      { id: "jessica-jones-season-1-e10", title: "AKA 1,000 Cuts", runtimeMinutes: 48 },
      { id: "jessica-jones-season-1-e11", title: "AKA I've Got the Blues", runtimeMinutes: 48 },
      { id: "jessica-jones-season-1-e12", title: "AKA Take a Bloody Number", runtimeMinutes: 48 },
      { id: "jessica-jones-season-1-e13", title: "AKA Smile", runtimeMinutes: 54 },
    ],
  },
  {
    id: "daredevil-season-2", title: "Daredevil (Season 2)", type: "show", releaseOrder: 27, timelineOrder: 17, section: "street-level",
    notes: "Netflix corner. Introduces Frank Castle (the Punisher) and Elektra.",
    episodes: [
      { id: "daredevil-season-2-e1", title: "Bang", runtimeMinutes: 54 },
      { id: "daredevil-season-2-e2", title: "Dogs to a Gunfight", runtimeMinutes: 50 },
      { id: "daredevil-season-2-e3", title: "New York's Finest", runtimeMinutes: 50 },
      { id: "daredevil-season-2-e4", title: "Penny and Dime", runtimeMinutes: 50 },
      { id: "daredevil-season-2-e5", title: "Kinbaku", runtimeMinutes: 50 },
      { id: "daredevil-season-2-e6", title: "Regrets Only", runtimeMinutes: 50 },
      { id: "daredevil-season-2-e7", title: "Semper Fidelis", runtimeMinutes: 50 },
      { id: "daredevil-season-2-e8", title: "Guilty as Sin", runtimeMinutes: 50 },
      { id: "daredevil-season-2-e9", title: "Seven Minutes in Heaven", runtimeMinutes: 50 },
      { id: "daredevil-season-2-e10", title: "The Man in the Box", runtimeMinutes: 50 },
      { id: "daredevil-season-2-e11", title: ".380", runtimeMinutes: 49 },
      { id: "daredevil-season-2-e12", title: "The Dark at the End of the Tunnel", runtimeMinutes: 50 },
      { id: "daredevil-season-2-e13", title: "A Cold Day in Hell's Kitchen", runtimeMinutes: 56, spoiler: "Elektra is killed by the Hand's ninjas, and Frank Castle takes up the Punisher identity for good — setting up his own series." },
    ],
  },
  {
    id: "punisher-season-1", title: "The Punisher (Season 1)", type: "show", releaseOrder: 28, timelineOrder: 24, section: "street-level",
    notes: "Netflix corner. Frank Castle's own series, spun off from Daredevil Season 2.",
    episodes: [
      { id: "punisher-season-1-e1", title: "3AM", runtimeMinutes: 52 },
      { id: "punisher-season-1-e2", title: "Two Dead Men", runtimeMinutes: 52 },
      { id: "punisher-season-1-e3", title: "Kandahar", runtimeMinutes: 52 },
      { id: "punisher-season-1-e4", title: "Resupply", runtimeMinutes: 52 },
      { id: "punisher-season-1-e5", title: "Gunner", runtimeMinutes: 52 },
      { id: "punisher-season-1-e6", title: "The Judas Goat", runtimeMinutes: 52 },
      { id: "punisher-season-1-e7", title: "Crosshairs", runtimeMinutes: 52 },
      { id: "punisher-season-1-e8", title: "Cold Steel", runtimeMinutes: 52 },
      { id: "punisher-season-1-e9", title: "Front Toward Enemy", runtimeMinutes: 52 },
      { id: "punisher-season-1-e10", title: "Virtue of the Vicious", runtimeMinutes: 52 },
      { id: "punisher-season-1-e11", title: "Danger Close", runtimeMinutes: 52 },
      { id: "punisher-season-1-e12", title: "Home", runtimeMinutes: 52 },
      { id: "punisher-season-1-e13", title: "Memento Mori", runtimeMinutes: 58 },
    ],
  },
  {
    id: "daredevil-season-3", title: "Daredevil (Season 3)", type: "show", releaseOrder: 29, timelineOrder: 25, section: "street-level",
    notes: "Netflix corner. Wilson Fisk works his way back to power from behind bars.",
    episodes: [
      { id: "daredevil-season-3-e1", title: "Resurrection", runtimeMinutes: 50 },
      { id: "daredevil-season-3-e2", title: "Please", runtimeMinutes: 50 },
      { id: "daredevil-season-3-e3", title: "No Good Deed", runtimeMinutes: 50 },
      { id: "daredevil-season-3-e4", title: "Blindsided", runtimeMinutes: 50 },
      { id: "daredevil-season-3-e5", title: "The Perfect Game", runtimeMinutes: 50 },
      { id: "daredevil-season-3-e6", title: "The Devil You Know", runtimeMinutes: 50 },
      { id: "daredevil-season-3-e7", title: "Aftermath", runtimeMinutes: 50 },
      { id: "daredevil-season-3-e8", title: "Upstairs/Downstairs", runtimeMinutes: 50 },
      { id: "daredevil-season-3-e9", title: "Revelations", runtimeMinutes: 50 },
      { id: "daredevil-season-3-e10", title: "Karen", runtimeMinutes: 50 },
      { id: "daredevil-season-3-e11", title: "Reunion", runtimeMinutes: 50 },
      { id: "daredevil-season-3-e12", title: "One Last Shot", runtimeMinutes: 50 },
      { id: "daredevil-season-3-e13", title: "A New Napkin", runtimeMinutes: 56, spoiler: "Wilson Fisk manipulates the FBI into freeing him and killing his handler, walking free with a plan to go legitimate — exactly the setup Daredevil: Born Again opens on years later." },
    ],
  },
  {
    id: "punisher-season-2", title: "The Punisher (Season 2)", type: "show", releaseOrder: 30, timelineOrder: 26, section: "street-level",
    notes: "Netflix corner. The last of this era before the story jumps to Daredevil: Born Again.",
    episodes: [
      { id: "punisher-season-2-e1", title: "Roadhouse Blues", runtimeMinutes: 52 },
      { id: "punisher-season-2-e2", title: "Fight or Flight", runtimeMinutes: 52 },
      { id: "punisher-season-2-e3", title: "Trouble the Water", runtimeMinutes: 52 },
      { id: "punisher-season-2-e4", title: "Scar Tissue", runtimeMinutes: 52 },
      { id: "punisher-season-2-e5", title: "One-Eyed Jacks", runtimeMinutes: 52 },
      { id: "punisher-season-2-e6", title: "Nakazat", runtimeMinutes: 52 },
      { id: "punisher-season-2-e7", title: "One Bad Day", runtimeMinutes: 52 },
      { id: "punisher-season-2-e8", title: "My Brother's Keeper", runtimeMinutes: 52 },
      { id: "punisher-season-2-e9", title: "Flustercluck", runtimeMinutes: 52 },
      { id: "punisher-season-2-e10", title: "The Dark Hearts of Men", runtimeMinutes: 52 },
      { id: "punisher-season-2-e11", title: "The Abyss", runtimeMinutes: 52 },
      { id: "punisher-season-2-e12", title: "Collision Course", runtimeMinutes: 52 },
      { id: "punisher-season-2-e13", title: "The Whirlwind", runtimeMinutes: 58 },
    ],
  },
  {
    id: "wandavision", title: "WandaVision", type: "show", releaseOrder: 31, timelineOrder: 32, section: "multiverse-saga", core: true,
    notes: "Sets up Wanda's arc for Doctor Strange in the Multiverse of Madness.",
    episodes: [
      { id: "wandavision-e1", title: "Filmed Before a Live Studio Audience", runtimeMinutes: 30 },
      { id: "wandavision-e2", title: "Don't Touch That Dial", runtimeMinutes: 37 },
      { id: "wandavision-e3", title: "Now in Color", runtimeMinutes: 33 },
      { id: "wandavision-e4", title: "We Interrupt This Program", runtimeMinutes: 35 },
      { id: "wandavision-e5", title: "On a Very Special Episode...", runtimeMinutes: 41 },
      { id: "wandavision-e6", title: "All-New Halloween Spooktacular!", runtimeMinutes: 38 },
      { id: "wandavision-e7", title: "Breaking the Fourth Wall", runtimeMinutes: 38, spoiler: "\"Agnes\" is revealed to be Agatha Harkness, a centuries-old witch who has been manipulating events from the start." },
      { id: "wandavision-e8", title: "Previously On", runtimeMinutes: 46 },
      { id: "wandavision-e9", title: "The Series Finale", runtimeMinutes: 50, spoiler: "Wanda becomes the Scarlet Witch and takes the Darkhold — directly setting up Doctor Strange in the Multiverse of Madness." },
    ],
  },
  {
    id: "falcon-and-winter-soldier", title: "The Falcon and the Winter Soldier", type: "show", releaseOrder: 32, timelineOrder: 33, section: "multiverse-saga", core: true,
    notes: "Sam Wilson takes up the Captain America shield.",
    episodes: [
      { id: "falcon-and-winter-soldier-e1", title: "New World Order", runtimeMinutes: 49 },
      { id: "falcon-and-winter-soldier-e2", title: "The Star-Spangled Man", runtimeMinutes: 50 },
      { id: "falcon-and-winter-soldier-e3", title: "Power Broker", runtimeMinutes: 53 },
      { id: "falcon-and-winter-soldier-e4", title: "The Whole World is Watching", runtimeMinutes: 50 },
      { id: "falcon-and-winter-soldier-e5", title: "Truth", runtimeMinutes: 60 },
      { id: "falcon-and-winter-soldier-e6", title: "One World, One People", runtimeMinutes: 50, spoiler: "Sam Wilson becomes the new Captain America, and Sharon Carter is revealed to be the Power Broker — a thread that resurfaces in Captain America: Brave New World and Thunderbolts*." },
    ],
  },
  {
    id: "loki-season-1", title: "Loki (Season 1)", type: "show", releaseOrder: 33, timelineOrder: 30, section: "multiverse-saga", core: true,
    notes: "Branches the multiverse — required viewing for everything that follows.",
    stopPoint: "Season 1 only, for now — do not continue into Loki Season 2 yet. It comes much later, after Ant-Man and the Wasp: Quantumania.",
    episodes: [
      { id: "loki-season-1-e1", title: "Glorious Purpose", runtimeMinutes: 52 },
      { id: "loki-season-1-e2", title: "The Variant", runtimeMinutes: 54 },
      { id: "loki-season-1-e3", title: "Lamentis", runtimeMinutes: 42 },
      { id: "loki-season-1-e4", title: "The Nexus Event", runtimeMinutes: 48 },
      { id: "loki-season-1-e5", title: "Journey into Mystery", runtimeMinutes: 49 },
      { id: "loki-season-1-e6", title: "For All Time. Always.", runtimeMinutes: 46, spoiler: "Loki meets He Who Remains, a Kang variant, at the end of time — his death fractures the Sacred Timeline into the multiverse that Doctor Strange 2, Loki Season 2, and eventually Doomsday all deal with." },
    ],
  },
  {
    id: "what-if-season-1", title: "What If...? (Season 1)", type: "show", releaseOrder: 34, timelineOrder: 31, section: "multiverse-saga",
    notes: "Season 1 picks up directly from Loki Season 1's shattered timeline and is treated as required viewing here — Seasons 2 and 3 are optional side quests instead.",
    episodes: [
      { id: "what-if-s1e1", title: "S1: What If... Captain Carter Were the First Avenger?", runtimeMinutes: 34 },
      { id: "what-if-s1e2", title: "S1: What If... T'Challa Became a Star-Lord?", runtimeMinutes: 32 },
      { id: "what-if-s1e3", title: "S1: What If... the World Lost Its Mightiest Heroes?", runtimeMinutes: 34 },
      { id: "what-if-s1e4", title: "S1: What If... Doctor Strange Lost His Heart Instead of His Hands?", runtimeMinutes: 32 },
      { id: "what-if-s1e5", title: "S1: What If... Zombies?!", runtimeMinutes: 32 },
      { id: "what-if-s1e6", title: "S1: What If... Killmonger Rescued Tony Stark?", runtimeMinutes: 31 },
      { id: "what-if-s1e7", title: "S1: What If... Thor Were an Only Child?", runtimeMinutes: 32 },
      { id: "what-if-s1e8", title: "S1: What If... Ultron Won?", runtimeMinutes: 34 },
      { id: "what-if-s1e9", title: "S1: What If... the Watcher Broke His Oath?", runtimeMinutes: 34 },
    ],
  },
  { id: "shang-chi", title: "Shang-Chi and the Legend of the Ten Rings", type: "movie", releaseOrder: 35, timelineOrder: 45, section: "multiverse-saga", core: true, runtimeMinutes: 132 },
  { id: "eternals", title: "Eternals", type: "movie", releaseOrder: 36, timelineOrder: 34, section: "multiverse-saga", runtimeMinutes: 156 },
  {
    id: "hawkeye", title: "Hawkeye", type: "show", releaseOrder: 37, timelineOrder: 47, section: "multiverse-saga",
    notes: "Introduces Kate Bishop.",
    stopPoint: "The most accurate split actually breaks this show in two: episodes 1-5 belong right here, before No Way Home, and the finale (episode 6) plays best saved for right after it. Watching all six now instead still works fine — the timing is just slightly less ideal.",
    episodes: [
      { id: "hawkeye-e1", title: "Never Meet Your Heroes", runtimeMinutes: 47 },
      { id: "hawkeye-e2", title: "Hide and Seek", runtimeMinutes: 51 },
      { id: "hawkeye-e3", title: "Echoes", runtimeMinutes: 43 },
      { id: "hawkeye-e4", title: "Partners, Am I Right?", runtimeMinutes: 45 },
      { id: "hawkeye-e5", title: "Ronin", runtimeMinutes: 44 },
      { id: "hawkeye-e6", title: "So This Is Christmas?", runtimeMinutes: 55, spoiler: "A post-credits scene reveals Wilson Fisk (Kingpin) survived being shot — setting up Echo and Daredevil: Born Again." },
    ],
  },
  { id: "spider-man-no-way-home", title: "Spider-Man: No Way Home", type: "movie", releaseOrder: 38, timelineOrder: 46, section: "multiverse-saga", core: true, runtimeMinutes: 148, notes: "The multiverse crossover that pulls in the Raimi and Webb-era Spider-Men.", spoiler: "Doctor Strange's spell erases the world's memory of Peter Parker — he starts over with no one, not even MJ or Ned, remembering he's Spider-Man." },
  {
    id: "moon-knight", title: "Moon Knight", type: "show", releaseOrder: 39, timelineOrder: 49, section: "multiverse-saga",
    notes: "Self-contained — minimal ties to the wider saga so far.",
    episodes: [
      { id: "moon-knight-e1", title: "The Goldfish Problem", runtimeMinutes: 47 },
      { id: "moon-knight-e2", title: "Summon the Suit", runtimeMinutes: 50 },
      { id: "moon-knight-e3", title: "The Friendly Type", runtimeMinutes: 50 },
      { id: "moon-knight-e4", title: "The Tomb", runtimeMinutes: 51 },
      { id: "moon-knight-e5", title: "Asylum", runtimeMinutes: 49 },
      { id: "moon-knight-e6", title: "Gods and Monsters", runtimeMinutes: 50 },
    ],
  },
  { id: "doctor-strange-multiverse-of-madness", title: "Doctor Strange in the Multiverse of Madness", type: "movie", releaseOrder: 40, timelineOrder: 50, section: "multiverse-saga", runtimeMinutes: 126, notes: "Introduces key multiverse rules that carry through to Doomsday." },
  {
    id: "ms-marvel", title: "Ms. Marvel", type: "show", releaseOrder: 41, timelineOrder: 51, section: "multiverse-saga",
    notes: "Sets up Kamala Khan ahead of The Marvels.",
    episodes: [
      { id: "ms-marvel-e1", title: "Generation Why", runtimeMinutes: 38 },
      { id: "ms-marvel-e2", title: "Crushed", runtimeMinutes: 39 },
      { id: "ms-marvel-e3", title: "Destined", runtimeMinutes: 37 },
      { id: "ms-marvel-e4", title: "Seeing Red", runtimeMinutes: 40 },
      { id: "ms-marvel-e5", title: "Time and Again", runtimeMinutes: 38 },
      { id: "ms-marvel-e6", title: "No Normal", runtimeMinutes: 40, spoiler: "A post-credits scene ties Kamala Khan's powers to mutant genetics, not just her bangle — connecting her to the X-Men thread Doomsday is expected to bring into the MCU." },
    ],
  },
  { id: "thor-love-and-thunder", title: "Thor: Love and Thunder", type: "movie", releaseOrder: 42, timelineOrder: 52, section: "multiverse-saga", core: true, runtimeMinutes: 119 },
  {
    id: "she-hulk", title: "She-Hulk: Attorney at Law", type: "show", releaseOrder: 43, timelineOrder: 53, section: "multiverse-saga",
    notes: "Mostly self-contained; the finale breaks the fourth wall.",
    episodes: [
      { id: "she-hulk-e1", title: "A Normal Amount of Rage", runtimeMinutes: 33 },
      { id: "she-hulk-e2", title: "Superhuman Law", runtimeMinutes: 34 },
      { id: "she-hulk-e3", title: "The People vs. Emil Blonsky", runtimeMinutes: 36 },
      { id: "she-hulk-e4", title: "Is This Not Real Magic?", runtimeMinutes: 33 },
      { id: "she-hulk-e5", title: "Mean, Green, and Straight Poured into These Jeans", runtimeMinutes: 32 },
      { id: "she-hulk-e6", title: "Just Jen", runtimeMinutes: 30 },
      { id: "she-hulk-e7", title: "The Retreat", runtimeMinutes: 35 },
      { id: "she-hulk-e8", title: "Ribbit and Rip It", runtimeMinutes: 36 },
      { id: "she-hulk-e9", title: "Whose Show Is This?", runtimeMinutes: 38, spoiler: "Jennifer breaks the fourth wall to confront the show's writers directly, and Matt Murdock (Daredevil) appears as a legal favor — connecting to Daredevil: Born Again." },
    ],
  },
  { id: "black-panther-wakanda-forever", title: "Black Panther: Wakanda Forever", type: "movie", releaseOrder: 44, timelineOrder: 54, section: "multiverse-saga", core: true, runtimeMinutes: 161 },
  { id: "ant-man-quantumania", title: "Ant-Man and the Wasp: Quantumania", type: "movie", releaseOrder: 45, timelineOrder: 56, section: "multiverse-saga", core: true, runtimeMinutes: 125 },
  {
    id: "loki-season-2", title: "Loki (Season 2)", type: "show", releaseOrder: 46, timelineOrder: 57, section: "multiverse-saga", core: true,
    notes: "Resolves the TVA storyline and reshapes the multiverse's branches.",
    episodes: [
      { id: "loki-season-2-e1", title: "Ouroboros", runtimeMinutes: 47 },
      { id: "loki-season-2-e2", title: "Breaking Brad", runtimeMinutes: 51 },
      { id: "loki-season-2-e3", title: "1893", runtimeMinutes: 55 },
      { id: "loki-season-2-e4", title: "Heart of the TVA", runtimeMinutes: 50 },
      { id: "loki-season-2-e5", title: "Science/Fiction", runtimeMinutes: 50 },
      { id: "loki-season-2-e6", title: "Glorious Purpose", runtimeMinutes: 58, spoiler: "Loki chooses to hold every branched timeline together himself on the Temporal Loom, becoming \"the god of stories\" — the multiverse's fragile new stability going into Doomsday rests on this choice." },
    ],
  },
  { id: "guardians-of-the-galaxy-vol-3", title: "Guardians of the Galaxy Vol. 3", type: "movie", releaseOrder: 47, timelineOrder: 58, section: "multiverse-saga", runtimeMinutes: 150 },
  {
    id: "secret-invasion", title: "Secret Invasion", type: "show", releaseOrder: 48, timelineOrder: 59, section: "multiverse-saga",
    notes: "Establishes the Skrull infiltration thread.",
    stopPoint: "Short on time? The finale (S1E6) alone covers what matters — the Skrull policy shift that ripples into later political plotlines. The other five episodes are setup you can skip without losing the thread.",
    episodes: [
      { id: "secret-invasion-e1", title: "Resurrection", runtimeMinutes: 43 },
      { id: "secret-invasion-e2", title: "Promises", runtimeMinutes: 45 },
      { id: "secret-invasion-e3", title: "Betrayed", runtimeMinutes: 42 },
      { id: "secret-invasion-e4", title: "Beloved", runtimeMinutes: 38 },
      { id: "secret-invasion-e5", title: "Harvest", runtimeMinutes: 40 },
      { id: "secret-invasion-e6", title: "Home", runtimeMinutes: 34, spoiler: "After a Skrull impersonating Rhodey is exposed, President Ritson declares all Skrulls enemies of the state — a xenophobic policy shift that ripples into later political plotlines." },
    ],
  },
  { id: "the-marvels", title: "The Marvels", type: "movie", releaseOrder: 49, timelineOrder: 60, section: "multiverse-saga", core: true, runtimeMinutes: 105 },
  {
    id: "echo", title: "Echo", type: "show", releaseOrder: 50, timelineOrder: 48, section: "multiverse-saga",
    notes: "Follow-up to Hawkeye's Kingpin/Maya Lopez thread.",
    episodes: [
      { id: "echo-e1", title: "Chafa", runtimeMinutes: 49 },
      { id: "echo-e2", title: "Lowak", runtimeMinutes: 39 },
      { id: "echo-e3", title: "Tuklo", runtimeMinutes: 42 },
      { id: "echo-e4", title: "Taloa", runtimeMinutes: 37 },
      { id: "echo-e5", title: "Maya", runtimeMinutes: 34, spoiler: "Wilson Fisk (Kingpin) survives Maya's attempt on his life and doubles down on his plans for New York — picked up directly in Daredevil: Born Again." },
    ],
  },
  { id: "x-men", title: "X-Men", type: "movie", releaseOrder: 51, timelineOrder: 36, section: "x-men-pack", core: true, runtimeMinutes: 104, notes: "Opens Fox's original X-Men series — folded into the multiverse alongside Deadpool & Wolverine and, reportedly, Doomsday itself." },
  { id: "x2-x-men-united", title: "X2: X-Men United", type: "movie", releaseOrder: 52, timelineOrder: 37, section: "x-men-pack", core: true, runtimeMinutes: 134 },
  { id: "x-men-last-stand", title: "X-Men: The Last Stand", type: "movie", releaseOrder: 53, timelineOrder: 38, section: "x-men-pack", core: true, runtimeMinutes: 104 },
  { id: "x-men-days-of-future-past", title: "X-Men: Days of Future Past", type: "movie", releaseOrder: 54, timelineOrder: 39, section: "x-men-pack", runtimeMinutes: 132 },
  { id: "deadpool", title: "Deadpool", type: "movie", releaseOrder: 55, timelineOrder: 40, section: "x-men-pack", runtimeMinutes: 108 },
  { id: "logan", title: "Logan", type: "movie", releaseOrder: 56, timelineOrder: 42, section: "x-men-pack", runtimeMinutes: 137 },
  { id: "deadpool-2", title: "Deadpool 2", type: "movie", releaseOrder: 57, timelineOrder: 41, section: "x-men-pack", runtimeMinutes: 119 },
  { id: "deadpool-and-wolverine", title: "Deadpool & Wolverine", type: "movie", releaseOrder: 58, timelineOrder: 43, section: "x-men-pack", core: true, runtimeMinutes: 128, notes: "Folds in Fox's X-Men-era multiverse — directly relevant to Doomsday's cast.", spoiler: "The Sacred Timeline is fractured wide open by the Time Variance Authority's collapse, and a wave of Fox-era X-Men and Deadpool variants get pulled into the main multiverse — exactly the door Avengers: Doomsday reportedly walks through." },
  {
    id: "agatha-all-along", title: "Agatha All Along", type: "show", releaseOrder: 59, timelineOrder: 61, section: "final-run",
    notes: "WandaVision spinoff following Agatha Harkness.",
    episodes: [
      { id: "agatha-all-along-e1", title: "Seekest Thou the Road", runtimeMinutes: 42 },
      { id: "agatha-all-along-e2", title: "Circle Sewn with Fate / Unlock Thy Hidden Gate", runtimeMinutes: 44 },
      { id: "agatha-all-along-e3", title: "Through Many Miles of Tricks and Trials", runtimeMinutes: 40 },
      { id: "agatha-all-along-e4", title: "If I Can't Reach You / Let My Song Teach You", runtimeMinutes: 43 },
      { id: "agatha-all-along-e5", title: "Darkest Hour, Wake Thy Power", runtimeMinutes: 41 },
      { id: "agatha-all-along-e6", title: "Familiar by Thy Side", runtimeMinutes: 39 },
      { id: "agatha-all-along-e7", title: "Death's Hand in Mine", runtimeMinutes: 45 },
      { id: "agatha-all-along-e8", title: "Follow Me, My Friend / To Glory at the End", runtimeMinutes: 48 },
      { id: "agatha-all-along-e9", title: "Maiden Mother Crone", runtimeMinutes: 50, spoiler: "Agatha sacrifices herself for Billy Maximoff and returns as a ghost; Billy sets off to find his twin brother Tommy, last seen erased from reality in WandaVision." },
    ],
  },
  { id: "captain-america-brave-new-world", title: "Captain America: Brave New World", type: "movie", releaseOrder: 60, timelineOrder: 62, section: "final-run", core: true, runtimeMinutes: 118 },
  {
    id: "daredevil-born-again", title: "Daredevil: Born Again (Season 1)", type: "show", releaseOrder: 61, timelineOrder: 63, section: "final-run",
    notes: "Wilson Fisk's rise sets up the political thread running through Thunderbolts*.",
    episodes: [
      { id: "daredevil-born-again-e1", title: "Heaven's Half Hour", runtimeMinutes: 52 },
      { id: "daredevil-born-again-e2", title: "Optics", runtimeMinutes: 48 },
      { id: "daredevil-born-again-e3", title: "The Hollow of His Hand", runtimeMinutes: 50 },
      { id: "daredevil-born-again-e4", title: "Sic Semper Systema", runtimeMinutes: 49 },
      { id: "daredevil-born-again-e5", title: "With Interest", runtimeMinutes: 51 },
      { id: "daredevil-born-again-e6", title: "Excessive Force", runtimeMinutes: 50 },
      { id: "daredevil-born-again-e7", title: "Art for Art's Sake", runtimeMinutes: 49 },
      { id: "daredevil-born-again-e8", title: "Isle of Joy", runtimeMinutes: 52 },
      { id: "daredevil-born-again-e9", title: "Straight to Hell", runtimeMinutes: 54, spoiler: "Wilson Fisk uses his position as mayor to outlaw vigilantes and orders Matt Murdock killed on sight — the authoritarian backdrop that carries into Season 2 and Thunderbolts*." },
    ],
  },
  { id: "thunderbolts", title: "Thunderbolts*", type: "movie", releaseOrder: 62, timelineOrder: 64, section: "final-run", core: true, runtimeMinutes: 126 },
  {
    id: "ironheart", title: "Ironheart", type: "show", releaseOrder: 63, timelineOrder: 55, section: "final-run",
    notes: "Introduces Riri Williams ahead of her expected role in the wider saga.",
    episodes: [
      { id: "ironheart-e1", title: "Take Me Home", runtimeMinutes: 38 },
      { id: "ironheart-e2", title: "Will the Real Natalie Please Stand Up?", runtimeMinutes: 37 },
      { id: "ironheart-e3", title: "We in Danger, Girl", runtimeMinutes: 39 },
      { id: "ironheart-e4", title: "Bad Magic", runtimeMinutes: 36 },
      { id: "ironheart-e5", title: "Karma's a Glitch", runtimeMinutes: 38 },
      { id: "ironheart-e6", title: "The Past Is the Past", runtimeMinutes: 42, spoiler: "Riri makes a literal deal with Mephisto — the MCU's first on-screen appearance of the demon — trading something of her own to bring Natalie back to life." },
    ],
  },
  { id: "fantastic-four-first-steps", title: "The Fantastic Four: First Steps", type: "movie", releaseOrder: 64, timelineOrder: 65, section: "final-run", core: true, runtimeMinutes: 115, notes: "Introduces Marvel's First Family ahead of their merge into the main timeline." },
  {
    id: "wonder-man", title: "Wonder Man", type: "show", releaseOrder: 65, timelineOrder: 66, section: "final-run",
    notes: "Mostly self-contained Hollywood satire about a stuntman chasing the role of a retired superhero.",
    episodes: [
      { id: "wonder-man-e1", title: "Matinee", runtimeMinutes: 36 },
      { id: "wonder-man-e2", title: "Self-Tape", runtimeMinutes: 34 },
      { id: "wonder-man-e3", title: "Pacoima", runtimeMinutes: 34 },
      { id: "wonder-man-e4", title: "Doorman", runtimeMinutes: 34 },
      { id: "wonder-man-e5", title: "Found Footage", runtimeMinutes: 34 },
      { id: "wonder-man-e6", title: "Call Back", runtimeMinutes: 34 },
      { id: "wonder-man-e7", title: "Kathy Friedman", runtimeMinutes: 34 },
      { id: "wonder-man-e8", title: "Yucca Valley", runtimeMinutes: 40 },
    ],
  },
  {
    id: "daredevil-born-again-season-2", title: "Daredevil: Born Again (Season 2)", type: "show", releaseOrder: 66, timelineOrder: 67, section: "final-run",
    notes: "Direct continuation of Season 1's cliffhanger.",
    episodes: [
      { id: "daredevil-born-again-season-2-e1", title: "The Northern Star", runtimeMinutes: 50 },
      { id: "daredevil-born-again-season-2-e2", title: "Shoot the Moon", runtimeMinutes: 50 },
      { id: "daredevil-born-again-season-2-e3", title: "The Scales & The Sword", runtimeMinutes: 50 },
      { id: "daredevil-born-again-season-2-e4", title: "Gloves Off", runtimeMinutes: 50 },
      { id: "daredevil-born-again-season-2-e5", title: "The Grand Design", runtimeMinutes: 50 },
      { id: "daredevil-born-again-season-2-e6", title: "Requiem", runtimeMinutes: 50 },
      { id: "daredevil-born-again-season-2-e7", title: "The Hateful Darkness", runtimeMinutes: 50 },
      { id: "daredevil-born-again-season-2-e8", title: "The Southern Cross", runtimeMinutes: 54, spoiler: "The season closes with Fisk's grip on New York shaken but not broken, and Frank Castle drawn back into the fight — picked up directly by The Punisher: One Last Kill." },
    ],
  },
  { id: "punisher-one-last-kill", title: "The Punisher: One Last Kill", type: "movie", releaseOrder: 67, timelineOrder: 68, section: "final-run", runtimeMinutes: 51, notes: "A one-off special, not a full series — Frank Castle's last word on the Born Again Season 2 fallout." },
  { id: "spider-man-brand-new-day", title: "Spider-Man: Brand New Day", type: "movie", releaseOrder: 68, timelineOrder: 69, section: "final-run", core: true, runtimeMinutes: 145 },
  {
    id: "visionquest", title: "VisionQuest", type: "show", releaseOrder: 69, timelineOrder: 35, section: "final-run", core: true,
    notes: "White Vision's search for his lost memories and humanity after WandaVision. Episode titles hadn't been announced as of this list's last update — shown as placeholders.",
    episodes: [
      { id: "visionquest-e1", title: "Episode 1", runtimeMinutes: 45 },
      { id: "visionquest-e2", title: "Episode 2", runtimeMinutes: 45 },
      { id: "visionquest-e3", title: "Episode 3", runtimeMinutes: 45 },
      { id: "visionquest-e4", title: "Episode 4", runtimeMinutes: 45 },
      { id: "visionquest-e5", title: "Episode 5", runtimeMinutes: 45 },
      { id: "visionquest-e6", title: "Episode 6", runtimeMinutes: 45 },
      { id: "visionquest-e7", title: "Episode 7", runtimeMinutes: 45 },
      { id: "visionquest-e8", title: "Episode 8", runtimeMinutes: 45 },
    ],
  },
  { id: "avengers-doomsday", title: "Avengers: Doomsday", type: "movie", releaseOrder: 70, timelineOrder: 70, section: "final-run", core: true, runtimeMinutes: 180, notes: "In theaters December 18, 2026. Runtime is an estimate — not yet officially confirmed." },
  { id: "spider-man-2002", title: "Spider-Man", type: "movie", releaseOrder: 71, timelineOrder: 71, section: "side-quests", optional: true, runtimeMinutes: 121, notes: "Optional side quest. Opens Sam Raimi's Spider-Man trilogy — this era resurfaces briefly in No Way Home's multiverse crossover, but isn't required to get there." },
  { id: "spider-man-2-2004", title: "Spider-Man 2", type: "movie", releaseOrder: 72, timelineOrder: 72, section: "side-quests", optional: true, runtimeMinutes: 127, notes: "Optional side quest. The second entry in Raimi's trilogy." },
  { id: "spider-man-3-2007", title: "Spider-Man 3", type: "movie", releaseOrder: 73, timelineOrder: 73, section: "side-quests", optional: true, runtimeMinutes: 139, notes: "Optional side quest. Closes out Raimi's trilogy." },
  { id: "amazing-spider-man", title: "The Amazing Spider-Man", type: "movie", releaseOrder: 74, timelineOrder: 74, section: "side-quests", optional: true, runtimeMinutes: 136, notes: "Optional side quest. Opens the Garfield-era duology, also touched on by No Way Home's crossover." },
  { id: "amazing-spider-man-2", title: "The Amazing Spider-Man 2", type: "movie", releaseOrder: 75, timelineOrder: 75, section: "side-quests", optional: true, runtimeMinutes: 142, notes: "Optional side quest. Closes out the Garfield-era duology." },
  { id: "x-men-origins-wolverine", title: "X-Men Origins: Wolverine", type: "movie", releaseOrder: 76, timelineOrder: 76, section: "side-quests", optional: true, runtimeMinutes: 107, notes: "Optional side quest. A Wolverine solo prequel set within Fox's original X-Men continuity." },
  { id: "x-men-first-class", title: "X-Men: First Class", type: "movie", releaseOrder: 77, timelineOrder: 77, section: "side-quests", optional: true, runtimeMinutes: 131, notes: "Optional side quest. A prequel reboot of the X-Men series — not required to follow the main line." },
  { id: "the-wolverine", title: "The Wolverine", type: "movie", releaseOrder: 78, timelineOrder: 78, section: "side-quests", optional: true, runtimeMinutes: 126, notes: "Optional side quest. Wolverine's second solo outing." },
  { id: "x-men-apocalypse", title: "X-Men: Apocalypse", type: "movie", releaseOrder: 79, timelineOrder: 79, section: "side-quests", optional: true, runtimeMinutes: 144, notes: "Optional side quest. Closes out the First Class prequel trilogy." },
  { id: "dark-phoenix", title: "Dark Phoenix", type: "movie", releaseOrder: 80, timelineOrder: 80, section: "side-quests", optional: true, runtimeMinutes: 113, notes: "Optional side quest. The final film of the pre-reboot X-Men series." },
  { id: "the-new-mutants", title: "The New Mutants", type: "movie", releaseOrder: 81, timelineOrder: 81, section: "side-quests", optional: true, runtimeMinutes: 94, notes: "Optional side quest. A standalone, horror-tinged spinoff only loosely tied to the wider X-Men series." },
  {
    id: "what-if-seasons-2-3", title: "What If...? (Seasons 2-3)", type: "show", releaseOrder: 82, timelineOrder: 82, section: "side-quests", optional: true,
    notes: "Optional side quest. Seasons 2 and 3 of the animated multiverse anthology — not required, and not directly referenced by anything later in the main sequence.",
    episodes: [
      { id: "what-if-s2e1", title: "S2: What If... Nebula Joined the Nova Corps?", runtimeMinutes: 31 },
      { id: "what-if-s2e2", title: "S2: What If... Peter Quill Attacked Earth's Mightiest Heroes?", runtimeMinutes: 31 },
      { id: "what-if-s2e3", title: "S2: What If... Happy Hogan Saved Christmas?", runtimeMinutes: 32 },
      { id: "what-if-s2e4", title: "S2: What If... Iron Man Crashed Into the Grandmaster?", runtimeMinutes: 31 },
      { id: "what-if-s2e5", title: "S2: What If... Captain Carter Fought the Hydra Stomper?", runtimeMinutes: 32 },
      { id: "what-if-s2e6", title: "S2: What If... Kahhori Reshaped the World?", runtimeMinutes: 33 },
      { id: "what-if-s2e7", title: "S2: What If... Hela Found the Ten Rings?", runtimeMinutes: 32 },
      { id: "what-if-s2e8", title: "S2: What If... the Avengers Assembled in 1602?", runtimeMinutes: 33 },
      { id: "what-if-s2e9", title: "S2: What If... Strange Supreme Intervened?", runtimeMinutes: 34 },
      { id: "what-if-s3e1", title: "S3: What If... the Hulk Fought the Mech Avengers?", runtimeMinutes: 32 },
      { id: "what-if-s3e2", title: "S3: What If... Agatha Went to Hollywood?", runtimeMinutes: 32 },
      { id: "what-if-s3e3", title: "S3: What If... the Red Guardian Stopped the Winter Soldier?", runtimeMinutes: 31 },
      { id: "what-if-s3e4", title: "S3: What If... Howard the Duck Got Hitched?", runtimeMinutes: 31 },
      { id: "what-if-s3e5", title: "S3: What If... the Emergence Destroyed the Earth?", runtimeMinutes: 33 },
      { id: "what-if-s3e6", title: "S3: What If... 1872?", runtimeMinutes: 32 },
      { id: "what-if-s3e7", title: "S3: What If... the Watcher Disappeared?", runtimeMinutes: 33 },
      { id: "what-if-s3e8", title: "S3: What If... (Series Finale)", runtimeMinutes: 35 },
    ],
  },
  {
    id: "agents-of-shield-season-1", title: "Agents of S.H.I.E.L.D. (Season 1)", type: "show", releaseOrder: 83, timelineOrder: 83, section: "side-quests", optional: true,
    notes: "Optional side quest. Agents of S.H.I.E.L.D. runs alongside nearly the entire MCU timeline (2013-2020) rather than one clean block — shown here as one contiguous chunk for simplicity.",
    episodes: [
      { id: "agents-of-shield-season-1-e1", title: "Pilot", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e2", title: "0-8-4", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e3", title: "The Asset", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e4", title: "Eye Spy", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e5", title: "Girl in the Flower Dress", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e6", title: "FZZT", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e7", title: "The Hub", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e8", title: "The Well", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e9", title: "Repairs", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e10", title: "The Bridge", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e11", title: "The Magical Place", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e12", title: "Seeds", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e13", title: "T.R.A.C.K.S.", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e14", title: "T.A.H.I.T.I.", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e15", title: "Yes Men", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e16", title: "End of the Beginning", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e17", title: "Turn, Turn, Turn", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e18", title: "Providence", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e19", title: "The Only Light in the Darkness", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e20", title: "Nothing Personal", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e21", title: "Ragtag", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-1-e22", title: "Beginning of the End", runtimeMinutes: 43 },
    ],
  },
  {
    id: "agents-of-shield-season-2", title: "Agents of S.H.I.E.L.D. (Season 2)", type: "show", releaseOrder: 84, timelineOrder: 84, section: "side-quests", optional: true,
    notes: "Optional side quest.",
    episodes: [
      { id: "agents-of-shield-season-2-e1", title: "Shadows", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e2", title: "Heavy Is the Head", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e3", title: "Making Friends and Influencing People", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e4", title: "Face My Enemy", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e5", title: "A Hen in the Wolf House", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e6", title: "A Fractured House", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e7", title: "The Writing on the Wall", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e8", title: "The Things We Bury", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e9", title: "...Ye Who Enter Here", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e10", title: "What They Become", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e11", title: "Aftershocks", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e12", title: "Who You Really Are", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e13", title: "One of Us", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e14", title: "Love in the Time of Hydra", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e15", title: "One Door Closes", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e16", title: "Afterlife", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e17", title: "Melinda", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e18", title: "The Frenemy of My Enemy", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e19", title: "The Dirty Half Dozen", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e20", title: "Scars", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e21", title: "S.O.S., Part 1", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-2-e22", title: "S.O.S., Part 2", runtimeMinutes: 43 },
    ],
  },
  {
    id: "agents-of-shield-season-3", title: "Agents of S.H.I.E.L.D. (Season 3)", type: "show", releaseOrder: 85, timelineOrder: 85, section: "side-quests", optional: true,
    notes: "Optional side quest.",
    episodes: [
      { id: "agents-of-shield-season-3-e1", title: "Laws of Nature", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e2", title: "Purpose in the Machine", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e3", title: "A Wanted (Inhu)man", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e4", title: "Devils You Know", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e5", title: "4,722 Hours", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e6", title: "Among Us Hide...", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e7", title: "Chaos Theory", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e8", title: "Many Heads, One Tale", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e9", title: "Closure", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e10", title: "Maveth", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e11", title: "Bouncing Back", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e12", title: "The Inside Man", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e13", title: "Parting Shot", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e14", title: "Watchdogs", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e15", title: "Spacetime", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e16", title: "Paradise Lost", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e17", title: "The Team", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e18", title: "The Singularity", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e19", title: "Failed Experiments", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e20", title: "Emancipation", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e21", title: "Absolution", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-3-e22", title: "Ascension", runtimeMinutes: 43 },
    ],
  },
  {
    id: "agents-of-shield-season-4", title: "Agents of S.H.I.E.L.D. (Season 4)", type: "show", releaseOrder: 86, timelineOrder: 86, section: "side-quests", optional: true,
    notes: "Optional side quest.",
    episodes: [
      { id: "agents-of-shield-season-4-e1", title: "The Ghost", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e2", title: "Meet the New Boss", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e3", title: "Uprising", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e4", title: "Let Me Stand Next to Your Fire", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e5", title: "Lockup", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e6", title: "The Good Samaritan", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e7", title: "Deals with Our Devils", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e8", title: "The Laws of Inferno Dynamics", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e9", title: "Broken Promises", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e10", title: "The Patriot", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e11", title: "Wake Up", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e12", title: "Hot Potato Soup", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e13", title: "BOOM", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e14", title: "The Man Behind the Shield", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e15", title: "Self Control", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e16", title: "What If...", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e17", title: "Identity and Change", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e18", title: "No Regrets", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e19", title: "All the Madame's Men", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e20", title: "Farewell, Cruel World!", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e21", title: "The Return", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-4-e22", title: "World's End", runtimeMinutes: 43 },
    ],
  },
  {
    id: "luke-cage-season-1", title: "Luke Cage (Season 1)", type: "show", releaseOrder: 87, timelineOrder: 87, section: "side-quests", optional: true,
    notes: "Optional side quest. Spins out of Jessica Jones Season 1.",
    episodes: [
      { id: "luke-cage-season-1-e1", title: "Moment of Truth", runtimeMinutes: 50 },
      { id: "luke-cage-season-1-e2", title: "Code of the Streets", runtimeMinutes: 50 },
      { id: "luke-cage-season-1-e3", title: "Who's Gonna Take the Weight?", runtimeMinutes: 50 },
      { id: "luke-cage-season-1-e4", title: "Step in the Arena", runtimeMinutes: 50 },
      { id: "luke-cage-season-1-e5", title: "Just to Get a Rep", runtimeMinutes: 50 },
      { id: "luke-cage-season-1-e6", title: "Suckas Need Bodyguards", runtimeMinutes: 50 },
      { id: "luke-cage-season-1-e7", title: "Manifest", runtimeMinutes: 50 },
      { id: "luke-cage-season-1-e8", title: "Blowin' Up the Spot", runtimeMinutes: 50 },
      { id: "luke-cage-season-1-e9", title: "DWYCK", runtimeMinutes: 50 },
      { id: "luke-cage-season-1-e10", title: "Take It Personal", runtimeMinutes: 50 },
      { id: "luke-cage-season-1-e11", title: "Now You're Mine", runtimeMinutes: 50 },
      { id: "luke-cage-season-1-e12", title: "Soliloquy of Chaos", runtimeMinutes: 50 },
      { id: "luke-cage-season-1-e13", title: "You Know My Steez", runtimeMinutes: 55 },
    ],
  },
  {
    id: "iron-fist-season-1", title: "Iron Fist (Season 1)", type: "show", releaseOrder: 88, timelineOrder: 88, section: "side-quests", optional: true,
    notes: "Optional side quest. Introduces Danny Rand ahead of The Defenders.",
    episodes: [
      { id: "iron-fist-season-1-e1", title: "Snow Gives Way", runtimeMinutes: 50 },
      { id: "iron-fist-season-1-e2", title: "Shadow Hawk Takes Flight", runtimeMinutes: 50 },
      { id: "iron-fist-season-1-e3", title: "Rolling Thunder Cannon Punch", runtimeMinutes: 50 },
      { id: "iron-fist-season-1-e4", title: "Eight Diagram Dragon Palm", runtimeMinutes: 50 },
      { id: "iron-fist-season-1-e5", title: "Under Leaf Pluck Lotus", runtimeMinutes: 50 },
      { id: "iron-fist-season-1-e6", title: "Immortal Emerges from Cave", runtimeMinutes: 50 },
      { id: "iron-fist-season-1-e7", title: "Felling Tree with Roots", runtimeMinutes: 50 },
      { id: "iron-fist-season-1-e8", title: "The Blessing of Many Fractures", runtimeMinutes: 50 },
      { id: "iron-fist-season-1-e9", title: "The Mistress of All Agonies", runtimeMinutes: 50 },
      { id: "iron-fist-season-1-e10", title: "Black Tiger Steals Heart", runtimeMinutes: 50 },
      { id: "iron-fist-season-1-e11", title: "Lead Horse Back to Stable", runtimeMinutes: 50 },
      { id: "iron-fist-season-1-e12", title: "Bar the Big Boss", runtimeMinutes: 50 },
      { id: "iron-fist-season-1-e13", title: "Dragon Plays with Fire", runtimeMinutes: 54 },
    ],
  },
  {
    id: "the-defenders", title: "The Defenders", type: "show", releaseOrder: 89, timelineOrder: 89, section: "side-quests", optional: true,
    notes: "Optional side quest. Daredevil, Jessica Jones, Luke Cage, and Iron Fist team up against the Hand.",
    episodes: [
      { id: "the-defenders-e1", title: "The H Word", runtimeMinutes: 48 },
      { id: "the-defenders-e2", title: "Mean Right Hook", runtimeMinutes: 48 },
      { id: "the-defenders-e3", title: "Worst Behavior", runtimeMinutes: 48 },
      { id: "the-defenders-e4", title: "Royal Dragon", runtimeMinutes: 48 },
      { id: "the-defenders-e5", title: "Take Shelter", runtimeMinutes: 48 },
      { id: "the-defenders-e6", title: "Ashes, Ashes", runtimeMinutes: 48 },
      { id: "the-defenders-e7", title: "Fish in the Jailhouse", runtimeMinutes: 48 },
      { id: "the-defenders-e8", title: "The Defenders", runtimeMinutes: 54 },
    ],
  },
  {
    id: "agents-of-shield-season-5", title: "Agents of S.H.I.E.L.D. (Season 5)", type: "show", releaseOrder: 90, timelineOrder: 90, section: "side-quests", optional: true,
    notes: "Optional side quest.",
    episodes: [
      { id: "agents-of-shield-season-5-e1", title: "Orientation, Part 1", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e2", title: "Orientation, Part 2", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e3", title: "A Life Spent", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e4", title: "A Life Earned", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e5", title: "Rewind", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e6", title: "Fun & Games", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e7", title: "Together or Not at All", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e8", title: "The Last Day", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e9", title: "Best Laid Plans", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e10", title: "Past Life", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e11", title: "All the Comforts of Home", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e12", title: "The Real Deal", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e13", title: "Principia", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e14", title: "The Devil Complex", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e15", title: "Rise and Shine", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e16", title: "Inside Voices", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e17", title: "The Honeymoon", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e18", title: "All Roads Lead...", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e19", title: "Option Two", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e20", title: "The One Who Will Save Us All", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e21", title: "The Force of Gravity", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-5-e22", title: "The End", runtimeMinutes: 43 },
    ],
  },
  {
    id: "jessica-jones-season-2", title: "Jessica Jones (Season 2)", type: "show", releaseOrder: 91, timelineOrder: 91, section: "side-quests", optional: true,
    notes: "Optional side quest.",
    episodes: [
      { id: "jessica-jones-season-2-e1", title: "AKA Start at the Beginning", runtimeMinutes: 48 },
      { id: "jessica-jones-season-2-e2", title: "AKA Freak Accident", runtimeMinutes: 48 },
      { id: "jessica-jones-season-2-e3", title: "AKA Sole Survivor", runtimeMinutes: 48 },
      { id: "jessica-jones-season-2-e4", title: "AKA God Help the Hobo", runtimeMinutes: 48 },
      { id: "jessica-jones-season-2-e5", title: "AKA The Octopus", runtimeMinutes: 48 },
      { id: "jessica-jones-season-2-e6", title: "AKA Facetime", runtimeMinutes: 48 },
      { id: "jessica-jones-season-2-e7", title: "AKA I Want Your Cray Cray", runtimeMinutes: 48 },
      { id: "jessica-jones-season-2-e8", title: "AKA Ain't We Got Fun", runtimeMinutes: 48 },
      { id: "jessica-jones-season-2-e9", title: "AKA Shark in the Bathtub, Monster in the Bed", runtimeMinutes: 48 },
      { id: "jessica-jones-season-2-e10", title: "AKA Pork Chop", runtimeMinutes: 48 },
      { id: "jessica-jones-season-2-e11", title: "AKA Three Lives and Counting", runtimeMinutes: 48 },
      { id: "jessica-jones-season-2-e12", title: "AKA Pray for My Patsy", runtimeMinutes: 48 },
      { id: "jessica-jones-season-2-e13", title: "AKA Playland", runtimeMinutes: 54 },
    ],
  },
  {
    id: "luke-cage-season-2", title: "Luke Cage (Season 2)", type: "show", releaseOrder: 92, timelineOrder: 92, section: "side-quests", optional: true,
    notes: "Optional side quest.",
    episodes: [
      { id: "luke-cage-season-2-e1", title: "Soul Brother #1", runtimeMinutes: 50 },
      { id: "luke-cage-season-2-e2", title: "Straighten It Out", runtimeMinutes: 50 },
      { id: "luke-cage-season-2-e3", title: "Wig Out", runtimeMinutes: 50 },
      { id: "luke-cage-season-2-e4", title: "I Get Physical", runtimeMinutes: 50 },
      { id: "luke-cage-season-2-e5", title: "All Souled Out", runtimeMinutes: 50 },
      { id: "luke-cage-season-2-e6", title: "The Basement", runtimeMinutes: 50 },
      { id: "luke-cage-season-2-e7", title: "On and On", runtimeMinutes: 50 },
      { id: "luke-cage-season-2-e8", title: "If It Ain't Rough, It Ain't Right", runtimeMinutes: 50 },
      { id: "luke-cage-season-2-e9", title: "For Pete's Sake", runtimeMinutes: 50 },
      { id: "luke-cage-season-2-e10", title: "The Main Ingredient", runtimeMinutes: 50 },
      { id: "luke-cage-season-2-e11", title: "The Creator", runtimeMinutes: 50 },
      { id: "luke-cage-season-2-e12", title: "Can't Front on Me", runtimeMinutes: 50 },
      { id: "luke-cage-season-2-e13", title: "They Reminisce Over You", runtimeMinutes: 55 },
    ],
  },
  {
    id: "iron-fist-season-2", title: "Iron Fist (Season 2)", type: "show", releaseOrder: 93, timelineOrder: 93, section: "side-quests", optional: true,
    notes: "Optional side quest.",
    episodes: [
      { id: "iron-fist-season-2-e1", title: "The Fury of Iron Fist", runtimeMinutes: 50 },
      { id: "iron-fist-season-2-e2", title: "The City's Not for Burning", runtimeMinutes: 50 },
      { id: "iron-fist-season-2-e3", title: "This Deadly Secret...", runtimeMinutes: 50 },
      { id: "iron-fist-season-2-e4", title: "Target: Iron Fist", runtimeMinutes: 50 },
      { id: "iron-fist-season-2-e5", title: "Heart of the Dragon", runtimeMinutes: 50 },
      { id: "iron-fist-season-2-e6", title: "The Dragon Dies at Dawn", runtimeMinutes: 50 },
      { id: "iron-fist-season-2-e7", title: "Morning of the Mindstorm", runtimeMinutes: 50 },
      { id: "iron-fist-season-2-e8", title: "Citadel on the Edge of Vengeance", runtimeMinutes: 50 },
      { id: "iron-fist-season-2-e9", title: "War Without End", runtimeMinutes: 50 },
      { id: "iron-fist-season-2-e10", title: "A Duel of Iron", runtimeMinutes: 54 },
    ],
  },
  {
    id: "agents-of-shield-season-6", title: "Agents of S.H.I.E.L.D. (Season 6)", type: "show", releaseOrder: 94, timelineOrder: 94, section: "side-quests", optional: true,
    notes: "Optional side quest.",
    episodes: [
      { id: "agents-of-shield-season-6-e1", title: "Missing Pieces", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-6-e2", title: "Window of Opportunity", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-6-e3", title: "Fear and Loathing on the Planet of Kitson", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-6-e4", title: "Code Yellow", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-6-e5", title: "The Other Thing", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-6-e6", title: "Inescapable", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-6-e7", title: "Toldja", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-6-e8", title: "Collision Course (Part I)", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-6-e9", title: "Collision Course (Part II)", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-6-e10", title: "Leap", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-6-e11", title: "From the Ashes", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-6-e12", title: "The Sign", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-6-e13", title: "New Life", runtimeMinutes: 43 },
    ],
  },
  {
    id: "jessica-jones-season-3", title: "Jessica Jones (Season 3)", type: "show", releaseOrder: 95, timelineOrder: 95, section: "side-quests", optional: true,
    notes: "Optional side quest.",
    episodes: [
      { id: "jessica-jones-season-3-e1", title: "A.K.A. The Perfect Burger", runtimeMinutes: 48 },
      { id: "jessica-jones-season-3-e2", title: "A.K.A. You're Welcome", runtimeMinutes: 48 },
      { id: "jessica-jones-season-3-e3", title: "A.K.A. I Have No Spleen", runtimeMinutes: 48 },
      { id: "jessica-jones-season-3-e4", title: "A.K.A. Customer Service Is Standing By", runtimeMinutes: 48 },
      { id: "jessica-jones-season-3-e5", title: "A.K.A. I Wish", runtimeMinutes: 48 },
      { id: "jessica-jones-season-3-e6", title: "A.K.A. Sorry Face", runtimeMinutes: 48 },
      { id: "jessica-jones-season-3-e7", title: "A.K.A. The Double Half-Wappinger", runtimeMinutes: 48 },
      { id: "jessica-jones-season-3-e8", title: "A.K.A. Camera Friendly", runtimeMinutes: 48 },
      { id: "jessica-jones-season-3-e9", title: "A.K.A. I Did Something Today", runtimeMinutes: 48 },
      { id: "jessica-jones-season-3-e10", title: "A.K.A. Hero Pants", runtimeMinutes: 48 },
      { id: "jessica-jones-season-3-e11", title: "A.K.A. Hellcat", runtimeMinutes: 48 },
      { id: "jessica-jones-season-3-e12", title: "A.K.A. A Lotta Worms", runtimeMinutes: 48 },
      { id: "jessica-jones-season-3-e13", title: "A.K.A. Everything", runtimeMinutes: 54 },
    ],
  },
  {
    id: "agents-of-shield-season-7", title: "Agents of S.H.I.E.L.D. (Season 7)", type: "show", releaseOrder: 96, timelineOrder: 96, section: "side-quests", optional: true,
    notes: "Optional side quest. The last of this era before the story jumps to Daredevil: Born Again.",
    episodes: [
      { id: "agents-of-shield-season-7-e1", title: "The New Deal", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-7-e2", title: "Know Your Onions", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-7-e3", title: "Alien Commies from the Future!", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-7-e4", title: "Out of the Past", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-7-e5", title: "A Trout in the Milk", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-7-e6", title: "Adapt or Die", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-7-e7", title: "The Totally Excellent Adventures of Mack and The D", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-7-e8", title: "After, Before", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-7-e9", title: "As I Have Always Been", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-7-e10", title: "Stolen", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-7-e11", title: "Brand New Day", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-7-e12", title: "The End Is at Hand", runtimeMinutes: 42 },
      { id: "agents-of-shield-season-7-e13", title: "What We're Fighting For", runtimeMinutes: 43 },
    ],
  },
];
